site_name: Stage 1 Handbook
theme:
  features:
    - content.code.copy
  name: material
  palette:
        # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/alicebraun


plugins:
    - search: {}
    - git-revision-date-localized
    - encryptcontent:
        global_password: 'icd11'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences


copyright: |
  &copy; 2024 Alice Braun | braun@broadinstitute.org  