site_name: My Docs
theme:
  name: material
  palette:
        # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/alicebraun

plugins:
    - search: {}
    - encryptcontent:
        global_password: 'your_password'

copyright: |
  &copy; 2024 Alice Braun  